Add redis in docker-compose
the-bug-factory/dora-the-explorer pull request #14
Opened 2020-02-15 19:56 UTC by ajie62

2020-02-17 07:19 UTC, ecourtial submitted a review, later dismissed

2020-02-17 07:19 UTC, ecourtial commented
@ajie62 Tu as réussi a t'y connecter? Genre un test basique avec l'extension PHP depuis le contrôleur frontal de Symfony?

2020-02-18 19:59 UTC, ArthurHoaro commented on docker-compose.yml
> +      - 6379:6379
Ça serait bien de rendre le port paramétrable sur le host, comme pour nginx, au cas où on a un redis local, ou si on veut démarrer plusieurs containers.

2020-02-18 20:15 UTC, leNEKO requested changes

2020-02-18 20:15 UTC, leNEKO commented on docker-compose.yml
> +      redis
```suggestion
      - redis
```

2020-02-18 20:21 UTC, leNEKO commented on docker-compose.yml
> +      - 6379:6379
aussi ce n'est peut être pas nécessaire d'exposer ce port ? au final on a uniquement besoin d'exposer nginx.

2020-02-18 20:53 UTC, ajie62 commented on docker-compose.yml
> +      - 6379:6379
Du coup, que ferait-il faire ? Garder `ports: - 6379:6379` ou le supprimer ?

2020-02-18 21:01 UTC, enrico69 commented on docker-compose.yml
> +      - 6379:6379
D'accord avec @ArthurHoaro . De la même manière que Nico (arrive pas à te taguer) avait suggéré pour Nginx, il faudrait rajouter une entrée dans le fichier environnement

2020-02-18 21:07 UTC, leNEKO commented on docker-compose.yml
> +      - 6379:6379
@leNEKO test

2020-02-18 21:36 UTC, ajie62 commented on docker-compose.yml
> +      - 6379:6379
Pas possible de te taguer non plus, Nico. Quand je tape @ et que j'essaie, je peux voir seulement Nicolas-Masson-Wizaplace.

2020-02-18 21:52 UTC, AurelienRasselet approved these changes

2020-02-19 07:14 UTC, ecourtial approved these changes

2020-02-19 08:26 UTC, ArthurHoaro approved these changes

2020-02-19 08:33 UTC, merged